import { redirect } from 'next/navigation';
import Link from 'next/link';
import { createServerSupabase } from '@/lib/supabase-server';
import { createServiceClient } from '@/lib/supabase';
import GenerateCodeForm from './GenerateCodeForm';
import { TRAINER_EMAILS } from '@/config/trainers';
import { courseConfigs } from '@/config/learn-modules';

export default async function LearnAdminPage({
  searchParams,
}: {
  searchParams?: Promise<{ course?: string }>;
}) {
  const resolvedParams = searchParams ? await searchParams : {};
  const requestedCourse = resolvedParams.course;
  const COURSE_ID =
    requestedCourse && requestedCourse in courseConfigs
      ? requestedCourse
      : 'ai-tools-mastery-beginners';
  const courseConfig = courseConfigs[COURSE_ID];
  // Auth + trainer check
  const supabase = await createServerSupabase();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user || !TRAINER_EMAILS.includes((user.email ?? '').toLowerCase())) {
    redirect('/login');
  }

  const db = createServiceClient();

  // Fetch active batches
  const { data: batches } = await db
    .from('batches')
    .select('id, center_name, start_date, status')
    .eq('status', 'active')
    .order('start_date', { ascending: false });

  const activeBatch = batches?.[0] ?? null;

  // Fetch active codes generated by this trainer
  const { data: activeCodes } = await db
    .from('daily_codes')
    .select('id, session_number, code, expires_at, batch_id')
    .eq('status', 'active')
    .eq('generated_by', user.id)
    .gt('expires_at', new Date().toISOString())
    .order('session_number', { ascending: true });

  // Fetch student progress: enrollments + unlocks + quiz scores
  // Only run these queries when an active batch exists
  let enrollments: { student_id: string; enrolled_at: string }[] = [];
  let unlocks: { student_id: string; session_number: number }[] = [];
  let scores: { student_id: string; percentage: number }[] = [];
  const userProfiles: Record<string, { email: string; name: string }> = {};

  if (activeBatch) {
    const { data: enrollmentData } = await db
      .from('learn_enrollments')
      .select('student_id, enrolled_at')
      .eq('course_id', COURSE_ID)
      .eq('batch_id', activeBatch.id)
      .is('completed_at', null);

    enrollments = enrollmentData ?? [];

    const studentIds = enrollments.map((e) => e.student_id);

    // Fetch unlocks and quiz scores for enrolled students
    const [unlocksResult, scoresResult] = await Promise.all([
      studentIds.length > 0
        ? db
            .from('session_unlocks')
            .select('student_id, session_number')
            .eq('course_id', COURSE_ID)
            .in('student_id', studentIds)
        : Promise.resolve({ data: [] }),
      studentIds.length > 0
        ? db
            .from('quiz_scores')
            .select('student_id, percentage')
            .eq('course_id', COURSE_ID)
            .in('student_id', studentIds)
        : Promise.resolve({ data: [] }),
    ]);

    unlocks = (unlocksResult.data ?? []) as typeof unlocks;
    scores = (scoresResult.data ?? []) as typeof scores;

    // Fetch user profiles from auth.users via service client
    if (studentIds.length > 0) {
      for (const id of studentIds) {
        const { data } = await db.auth.admin.getUserById(id);
        if (data?.user) {
          userProfiles[id] = {
            email: data.user.email ?? 'Unknown',
            name:
              (data.user.user_metadata?.full_name as string) ||
              (data.user.user_metadata?.name as string) ||
              data.user.email?.split('@')[0] ||
              'Unknown',
          };
        }
      }
    }
  }

  // Build student rows
  const studentRows = enrollments.map((enrollment) => {
    const sid = enrollment.student_id;
    const profile = userProfiles[sid] ?? { email: 'Unknown', name: 'Unknown' };
    const studentUnlocks = unlocks.filter((u) => u.student_id === sid);
    const studentScores = scores.filter((s) => s.student_id === sid);
    const quizAverage =
      studentScores.length > 0
        ? Math.round(
            studentScores.reduce((sum, s) => sum + s.percentage, 0) / studentScores.length
          )
        : null;
    return {
      id: sid,
      name: profile.name,
      email: profile.email,
      sessionsUnlocked: studentUnlocks.length,
      quizAverage,
    };
  });

  return (
    <div className="min-h-screen bg-[#020617] text-white">
      <div className="max-w-5xl mx-auto px-4 py-10">

        {/* Header */}
        <div className="mb-6 flex items-start justify-between gap-4">
          <div>
            <h1 className="text-2xl font-bold text-white">Trainer Dashboard</h1>
            <p className="text-gray-400 text-sm mt-1">
              TARAhut Learning Engine — internal trainer view
            </p>
          </div>
          <Link
            href="/learn/admin/promos"
            className="shrink-0 inline-flex items-center gap-1.5 rounded-lg border border-emerald-400/40 bg-emerald-500/10 px-3 py-1.5 text-xs font-semibold text-emerald-300 transition-colors hover:bg-emerald-500/15"
          >
            Promo codes →
          </Link>
        </div>

        {/* Course tabs */}
        <div className="mb-6 flex gap-2 flex-wrap">
          {Object.values(courseConfigs).map((cfg) => (
            <Link
              key={cfg.id}
              href={`/learn/admin?course=${cfg.id}`}
              className={`rounded-lg px-4 py-2 text-sm font-semibold transition ${
                cfg.id === COURSE_ID
                  ? 'bg-slate-900 text-white'
                  : 'border border-white/[0.08] text-gray-300 hover:border-slate-400'
              }`}
            >
              {cfg.title}
            </Link>
          ))}
        </div>

        {/* Batch info */}
        {activeBatch ? (
          <div className="bg-white/[0.03] rounded-xl border border-white/[0.08] p-5 mb-6">
            <h2 className="text-sm font-semibold text-gray-400 uppercase tracking-wide mb-3">
              Active Batch
            </h2>
            <p className="font-semibold text-white">{activeBatch.center_name}</p>
            <p className="text-sm text-gray-400 mt-0.5">
              Started:{' '}
              {new Date(activeBatch.start_date).toLocaleDateString('en-IN', {
                day: 'numeric',
                month: 'long',
                year: 'numeric',
              })}
            </p>
            <p className="text-sm text-gray-400 mt-0.5">
              Students enrolled: {enrollments.length}
            </p>
          </div>
        ) : (
          <div className="bg-amber-50 border border-amber-200 rounded-xl p-5 mb-6 text-amber-800 text-sm">
            No active batch found. Create a batch in Supabase first.
          </div>
        )}

        {/* Generate Code */}
        {activeBatch && (
          <div className="bg-white/[0.03] rounded-xl border border-white/[0.08] p-5 mb-6">
            <h2 className="text-sm font-semibold text-gray-400 uppercase tracking-wide mb-4">
              Generate Daily Code
            </h2>
            <GenerateCodeForm batchId={activeBatch.id} />
          </div>
        )}

        {/* Active Codes */}
        {(activeCodes?.length ?? 0) > 0 && (
          <div className="bg-white/[0.03] rounded-xl border border-white/[0.08] p-5 mb-6">
            <h2 className="text-sm font-semibold text-gray-400 uppercase tracking-wide mb-4">
              Active Codes
            </h2>
            <div className="space-y-3">
              {activeCodes!.map((c) => (
                <div
                  key={c.id}
                  className="flex items-center justify-between bg-[#020617] rounded-lg px-4 py-3"
                >
                  <div>
                    <span className="text-sm text-gray-400">Session {c.session_number}</span>
                  </div>
                  <div className="text-center">
                    <span className="font-mono text-3xl font-bold tracking-widest text-emerald-400">
                      {c.code}
                    </span>
                  </div>
                  <div className="text-right">
                    <span className="text-xs text-gray-500">
                      Expires{' '}
                      {new Date(c.expires_at).toLocaleTimeString('en-IN', {
                        hour: '2-digit',
                        minute: '2-digit',
                      })}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Student Progress Table */}
        <div className="bg-white/[0.03] rounded-xl border border-white/[0.08] overflow-hidden">
          <div className="px-5 py-4 border-b border-white/[0.05]">
            <h2 className="text-sm font-semibold text-gray-400 uppercase tracking-wide">
              Student Progress
            </h2>
          </div>
          {studentRows.length === 0 ? (
            <p className="text-gray-500 text-sm p-5">No enrolled students yet.</p>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead className="bg-[#020617] text-gray-400 text-xs uppercase tracking-wide">
                  <tr>
                    <th className="text-left px-5 py-3 font-medium">Student</th>
                    <th className="text-left px-5 py-3 font-medium">Email</th>
                    <th className="text-center px-5 py-3 font-medium">Sessions Unlocked</th>
                    <th className="text-center px-5 py-3 font-medium">Quiz Average</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {studentRows.map((student) => (
                    <tr key={student.id} className="hover:bg-[#020617] transition-colors">
                      <td className="px-5 py-3 font-medium text-white">{student.name}</td>
                      <td className="px-5 py-3 text-gray-400">{student.email}</td>
                      <td className="px-5 py-3 text-center">
                        <span className="inline-block bg-emerald-500/10 text-emerald-300 font-semibold rounded-full px-3 py-0.5 text-xs">
                          {student.sessionsUnlocked} / {courseConfig.totalSessions}
                        </span>
                      </td>
                      <td className="px-5 py-3 text-center">
                        {student.quizAverage !== null ? (
                          <span
                            className={`inline-block font-semibold rounded-full px-3 py-0.5 text-xs ${
                              student.quizAverage >= 90
                                ? 'bg-emerald-500/10 text-emerald-300'
                                : student.quizAverage >= 70
                                ? 'bg-amber-50 text-amber-700'
                                : 'bg-red-50 text-red-700'
                            }`}
                          >
                            {student.quizAverage}%
                          </span>
                        ) : (
                          <span className="text-gray-500 text-xs">No quizzes</span>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
