// "Your first AI conversation" — surfaces the most recent learn_artifacts row
// for Session 1, so the student sees their first real Claude exchange every
// time they land on the dashboard. This is the single ₹999-justifying artifact
// for the v1 live-playground rollout. If we add playgrounds to more sessions
// later, generalize this into a multi-session timeline.

interface FirstConversationCardProps {
  prompt: string;
  response: string;
  createdAt: string;
}

function truncate(text: string, max: number): string {
  const trimmed = text.trim();
  if (trimmed.length <= max) return trimmed;
  return trimmed.slice(0, max - 1).trimEnd() + '…';
}

export function FirstConversationCard({
  prompt,
  response,
  createdAt,
}: FirstConversationCardProps) {
  const dateLabel = new Date(createdAt).toLocaleDateString('en-IN', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });

  return (
    <div className="mb-10 rounded-2xl border border-[#00f0ff]/30 bg-gradient-to-br from-[#00f0ff]/[0.04] to-[#a855f7]/[0.03] p-6">
      <div className="mb-4 flex flex-wrap items-center gap-3">
        <span className="text-lg" aria-hidden>
          💬
        </span>
        <p className="text-xs font-semibold uppercase tracking-wider text-[#00f0ff]">
          Your First AI Conversation
        </p>
        <span className="ml-auto text-xs text-[#94a3b8]">{dateLabel}</span>
      </div>

      <div className="mb-3">
        <p className="mb-1 text-xs font-mono uppercase tracking-wider text-[#94a3b8]">
          You asked
        </p>
        <p className="text-sm leading-relaxed text-[#e2e8f0]">
          {truncate(prompt, 220)}
        </p>
      </div>

      <div className="rounded-lg border border-white/[0.06] bg-black/20 p-4">
        <p className="mb-1 text-xs font-mono uppercase tracking-wider text-[#a855f7]">
          Claude replied
        </p>
        <p className="whitespace-pre-line text-sm leading-relaxed text-[#cbd5e1]">
          {truncate(response, 480)}
        </p>
      </div>

      <p className="mt-4 text-xs italic text-[#94a3b8]">
        This is real — generated by Claude, saved to your account. The skill of the decade, on Day 1.
      </p>
    </div>
  );
}
