-- TARAhut Learning Engine — Database Tables
-- Run this in your Supabase SQL Editor

-- Batches (groups of students in a course)
CREATE TABLE IF NOT EXISTS batches (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  course_id TEXT NOT NULL DEFAULT 'ai-tools-mastery-beginners',
  trainer_id UUID REFERENCES auth.users(id),
  center_name TEXT DEFAULT 'TARAhut AI Labs Kotkapura',
  start_date DATE NOT NULL,
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'completed', 'cancelled')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Student enrollments in batches
CREATE TABLE IF NOT EXISTS learn_enrollments (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  student_id UUID NOT NULL REFERENCES auth.users(id),
  course_id TEXT NOT NULL DEFAULT 'ai-tools-mastery-beginners',
  batch_id UUID REFERENCES batches(id),
  enrolled_at TIMESTAMPTZ DEFAULT NOW(),
  completed_at TIMESTAMPTZ,
  UNIQUE(student_id, course_id)
);

-- Session unlocks (one row per student per session)
CREATE TABLE IF NOT EXISTS session_unlocks (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  student_id UUID NOT NULL REFERENCES auth.users(id),
  course_id TEXT NOT NULL DEFAULT 'ai-tools-mastery-beginners',
  session_number INTEGER NOT NULL CHECK (session_number BETWEEN 1 AND 16),
  unlocked_at TIMESTAMPTZ DEFAULT NOW(),
  unlock_code_used TEXT,
  UNIQUE(student_id, course_id, session_number)
);

-- Daily codes (generated by trainer per session)
CREATE TABLE IF NOT EXISTS daily_codes (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  batch_id UUID REFERENCES batches(id),
  session_number INTEGER NOT NULL CHECK (session_number BETWEEN 1 AND 16),
  code TEXT NOT NULL,
  generated_at TIMESTAMPTZ DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL,
  generated_by UUID REFERENCES auth.users(id),
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'expired', 'used'))
);

-- Quiz scores (upserted — one row per student per session)
CREATE TABLE IF NOT EXISTS quiz_scores (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  student_id UUID NOT NULL REFERENCES auth.users(id),
  course_id TEXT NOT NULL DEFAULT 'ai-tools-mastery-beginners',
  session_number INTEGER NOT NULL,
  score INTEGER NOT NULL,
  total INTEGER NOT NULL,
  percentage INTEGER NOT NULL,
  completed_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(student_id, course_id, session_number)
);

-- Achievements / badges earned by students
CREATE TABLE IF NOT EXISTS achievements (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  student_id UUID NOT NULL REFERENCES auth.users(id),
  badge_type TEXT NOT NULL,
  badge_name TEXT NOT NULL,
  earned_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(student_id, badge_type)
);

-- ────────────────────────────────────────────────────────────
-- Row Level Security
-- ────────────────────────────────────────────────────────────

ALTER TABLE batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE learn_enrollments ENABLE ROW LEVEL SECURITY;
ALTER TABLE session_unlocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE quiz_scores ENABLE ROW LEVEL SECURITY;
ALTER TABLE achievements ENABLE ROW LEVEL SECURITY;

-- Students can read their own data
CREATE POLICY "Students read own enrollments"
  ON learn_enrollments FOR SELECT
  USING (auth.uid() = student_id);

CREATE POLICY "Students read own unlocks"
  ON session_unlocks FOR SELECT
  USING (auth.uid() = student_id);

CREATE POLICY "Students read own scores"
  ON quiz_scores FOR SELECT
  USING (auth.uid() = student_id);

CREATE POLICY "Students read own achievements"
  ON achievements FOR SELECT
  USING (auth.uid() = student_id);

-- Active daily codes are readable by any authenticated user (for unlock validation)
CREATE POLICY "Authenticated users read active codes"
  ON daily_codes FOR SELECT
  TO authenticated
  USING (status = 'active' AND expires_at > NOW());

-- Batches are readable by authenticated users
CREATE POLICY "Authenticated users read batches"
  ON batches FOR SELECT
  TO authenticated
  USING (true);

-- Service role bypasses RLS for all API route operations (no policy needed)

-- ────────────────────────────────────────────────────────────
-- Indexes for common query patterns
-- ────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_session_unlocks_student_course
  ON session_unlocks (student_id, course_id);

CREATE INDEX IF NOT EXISTS idx_quiz_scores_student_course
  ON quiz_scores (student_id, course_id);

CREATE INDEX IF NOT EXISTS idx_achievements_student
  ON achievements (student_id);

CREATE INDEX IF NOT EXISTS idx_daily_codes_active
  ON daily_codes (status, expires_at)
  WHERE status = 'active';

CREATE INDEX IF NOT EXISTS idx_learn_enrollments_batch
  ON learn_enrollments (batch_id, course_id);
