export interface LearnModule {
  session: number;
  title: string;
  description: string;
  week: number;
  tools: string[];
  isFree: boolean;
  deliverable: string;
  previewQuestions: { q: string; options: string[]; answer: number }[];
}

export const learnModules: LearnModule[] = [
  {
    session: 1,
    title: 'What is AI?',
    description: 'Understand AI, meet ChatGPT, Claude & Gemini',
    week: 1,
    tools: ['ChatGPT', 'Claude', 'Gemini'],
    isFree: true,
    deliverable: 'First AI conversations + understanding of AI types',
    previewQuestions: [
      { q: 'What does AI stand for?', options: ['Automatic Intelligence', 'Artificial Intelligence', 'Advanced Internet'], answer: 1 },
      { q: 'Which of these is an AI tool?', options: ['Microsoft Word', 'ChatGPT', 'Calculator'], answer: 1 },
      { q: 'Can AI replace human creativity completely?', options: ['Yes, very soon', 'No, it augments human creativity', 'Only in art'], answer: 1 },
    ],
  },
  {
    session: 2,
    title: 'The AI Mindset',
    description: 'Ethics, careers, and the right approach to AI',
    week: 1,
    tools: [],
    isFree: false,
    deliverable: 'AI career plan + responsible use pledge',
    previewQuestions: [
      { q: 'What is the most important thing when using AI at work?', options: ['Speed', 'Responsibility & accuracy checks', 'Using the most expensive tool'], answer: 1 },
      { q: 'AI hallucination means AI…', options: ['Gets tired', 'Generates false information confidently', 'Only works at night'], answer: 1 },
      { q: 'Which skill becomes MORE valuable when AI exists?', options: ['Typing speed', 'Critical thinking', 'Memorizing facts'], answer: 1 },
    ],
  },
  {
    session: 3,
    title: 'Prompt Engineering Basics',
    description: 'The RCTF framework for better AI outputs',
    week: 1,
    tools: ['ChatGPT', 'Claude'],
    isFree: false,
    deliverable: '20 structured prompts using RCTF framework',
    previewQuestions: [
      { q: 'What does RCTF stand for in prompting?', options: ['Role, Context, Task, Format', 'Request, Create, Test, Fix', 'Read, Confirm, Think, Finish'], answer: 0 },
      { q: 'A vague prompt gives you…', options: ['Precise results', 'Vague, generic results', 'Better creativity'], answer: 1 },
      { q: 'Which prompt is better?', options: ['"Write something"', '"Write a 3-sentence email to a client apologizing for a delay"', '"Email about delay"'], answer: 1 },
    ],
  },
  {
    session: 4,
    title: 'Advanced Prompting',
    description: 'Chain-of-thought, few-shot, and prompt libraries',
    week: 1,
    tools: ['ChatGPT', 'Claude', 'Gemini'],
    isFree: false,
    deliverable: 'Personal prompt library with 30+ categorized prompts',
    previewQuestions: [
      { q: 'What is "few-shot" prompting?', options: ['Using AI only a few times', 'Giving AI examples to follow', 'Writing short prompts'], answer: 1 },
      { q: 'Chain-of-thought prompting helps AI…', options: ['Write shorter answers', 'Reason step-by-step through problems', 'Use less energy'], answer: 1 },
      { q: 'A prompt library is useful because…', options: ['It costs less', 'It saves time by reusing proven prompts', 'AI prefers libraries'], answer: 1 },
    ],
  },
  {
    session: 5,
    title: 'Mastering ChatGPT & Claude',
    description: 'Deep dive into the two most powerful AI tools',
    week: 2,
    tools: ['ChatGPT', 'Claude'],
    isFree: false,
    deliverable: 'Tool comparison report: 5 tasks on both tools',
    previewQuestions: [
      { q: 'ChatGPT was created by…', options: ['Google', 'OpenAI', 'Microsoft'], answer: 1 },
      { q: 'Claude is known for being especially…', options: ['Fast at math', 'Safe and nuanced in responses', 'Best for image generation'], answer: 1 },
      { q: 'When should you use both ChatGPT and Claude?', options: ['Never, pick one', 'When you want to compare outputs for quality', 'Only for coding'], answer: 1 },
    ],
  },
  {
    session: 6,
    title: 'AI for Professional Writing',
    description: 'Emails, resumes, proposals with AI',
    week: 2,
    tools: ['ChatGPT', 'Claude'],
    isFree: false,
    deliverable: 'Professional email set + AI-optimized resume',
    previewQuestions: [
      { q: 'When using AI to write a professional email, you should…', options: ['Send it immediately without reading', 'Review and personalize before sending', 'Use the longest version'], answer: 1 },
      { q: 'AI can help improve your resume by…', options: ['Adding fake experience', 'Optimizing for keywords and clarity', 'Changing your name'], answer: 1 },
      { q: 'Which tone is best for a client proposal?', options: ['Casual and funny', 'Professional and solution-focused', 'Very formal and long'], answer: 1 },
    ],
  },
  {
    session: 7,
    title: 'AI Research Tools',
    description: 'Perplexity and NotebookLM for deep research',
    week: 2,
    tools: ['Perplexity', 'NotebookLM'],
    isFree: false,
    deliverable: 'Cited research report using Perplexity + NotebookLM',
    previewQuestions: [
      { q: 'Perplexity AI is best described as…', options: ['An image generator', 'An AI-powered search engine with citations', 'A video editor'], answer: 1 },
      { q: 'NotebookLM lets you…', options: ['Generate images from text', 'Chat with your own uploaded documents', 'Schedule social media posts'], answer: 1 },
      { q: 'Why are citations important in AI research?', options: ['They make documents longer', 'They let you verify the source and accuracy', 'AI requires them to function'], answer: 1 },
    ],
  },
  {
    session: 8,
    title: 'Presentations & Design',
    description: 'Gamma and Canva AI for visual content',
    week: 2,
    tools: ['Gamma', 'Canva AI'],
    isFree: false,
    deliverable: '10-slide pitch deck + social media graphics',
    previewQuestions: [
      { q: 'Gamma AI helps you…', options: ['Edit videos', 'Create presentations from a text prompt', 'Write code'], answer: 1 },
      { q: 'The rule of thumb for slides is…', options: ['As much text as possible', 'One clear idea per slide', 'Only use images, no text'], answer: 1 },
      { q: 'Canva AI\'s "Magic Design" feature…', options: ['Requires design experience', 'Generates design templates from your content', 'Only works on desktop'], answer: 1 },
    ],
  },
  {
    session: 9,
    title: 'AI Image Generation',
    description: 'Midjourney, Ideogram, and Canva AI for images',
    week: 3,
    tools: ['Midjourney', 'Ideogram', 'Canva AI'],
    isFree: false,
    deliverable: '10 brand images across multiple AI tools',
    previewQuestions: [
      { q: 'Ideogram is especially good at…', options: ['Writing code', 'Generating images with readable text', 'Making videos'], answer: 1 },
      { q: 'A good image prompt includes…', options: ['Just the subject name', 'Subject, style, mood, and composition', 'Only colors'], answer: 1 },
      { q: 'AI-generated images can be used for…', options: ['Only personal use', 'Business branding, marketing, and content (check license)', 'Nothing commercial'], answer: 1 },
    ],
  },
  {
    session: 10,
    title: 'AI Video Creation',
    description: 'HeyGen avatars and CapCut editing',
    week: 3,
    tools: ['HeyGen', 'CapCut'],
    isFree: false,
    deliverable: '60-second AI avatar brand video',
    previewQuestions: [
      { q: 'HeyGen allows you to…', options: ['Generate music', 'Create AI avatar videos that speak your script', 'Build websites'], answer: 1 },
      { q: 'A 60-second brand video should focus on…', options: ['Every feature of your product', 'One clear message or call-to-action', 'Only showing your logo'], answer: 1 },
      { q: 'CapCut is used for…', options: ['Writing scripts', 'Editing and enhancing video content', 'Generating avatars'], answer: 1 },
    ],
  },
  {
    session: 11,
    title: 'AI Audio + Social Media',
    description: 'ElevenLabs voiceovers and content workflows',
    week: 3,
    tools: ['ElevenLabs'],
    isFree: false,
    deliverable: 'Brand audio kit + 7-day content calendar',
    previewQuestions: [
      { q: 'ElevenLabs is best known for…', options: ['Making images', 'Generating realistic AI voiceovers', 'Writing blog posts'], answer: 1 },
      { q: 'A content calendar helps you…', options: ['Post randomly when inspired', 'Plan and schedule consistent content', 'Delete old posts'], answer: 1 },
      { q: 'For social media, shorter content tends to…', options: ['Perform worse', 'Perform better due to attention spans', 'Only work on Twitter'], answer: 1 },
    ],
  },
  {
    session: 12,
    title: 'Brand Kit Project',
    description: 'Create a complete brand identity with AI',
    week: 3,
    tools: ['All tools'],
    isFree: false,
    deliverable: 'Complete brand identity for a local business',
    previewQuestions: [
      { q: 'A brand kit typically includes…', options: ['Just a logo', 'Logo, colors, fonts, and brand voice', 'Only social media posts'], answer: 1 },
      { q: 'Brand consistency means…', options: ['Using the same tool every day', 'Looking and sounding the same across all platforms', 'Only using one color'], answer: 1 },
      { q: 'When creating for a local business, you should…', options: ['Copy a global brand style', 'Research the local audience and competitors first', 'Use the most trendy design'], answer: 1 },
    ],
  },
  {
    session: 13,
    title: 'No-Code Website Building',
    description: 'Build websites with Bolt.new',
    week: 4,
    tools: ['Bolt.new'],
    isFree: false,
    deliverable: 'Live personal portfolio website',
    previewQuestions: [
      { q: 'Bolt.new lets you build websites by…', options: ['Writing complex code', 'Describing what you want in plain English', 'Hiring a developer'], answer: 1 },
      { q: 'A portfolio website should showcase…', options: ['Everything you have ever done', 'Your best 3-5 projects with results', 'Only your resume'], answer: 1 },
      { q: 'No-code tools are useful because…', options: ['They are always free', 'Non-developers can build functional websites quickly', 'They have no limitations'], answer: 1 },
    ],
  },
  {
    session: 14,
    title: 'Capstone Project',
    description: 'Real client brief — deliver a complete solution',
    week: 4,
    tools: ['All tools'],
    isFree: false,
    deliverable: 'Complete AI solution for a real client brief',
    previewQuestions: [
      { q: 'The capstone project is important because…', options: ['It gives you a certificate immediately', 'It proves you can deliver real-world AI work', 'It is the easiest session'], answer: 1 },
      { q: 'When working on a client brief, you should first…', options: ['Start designing immediately', 'Understand the client\'s goals and audience', 'Use as many AI tools as possible'], answer: 1 },
      { q: 'Delivering a complete solution means…', options: ['Sending a rough draft', 'Presenting a polished, client-ready output', 'Using only one AI tool'], answer: 1 },
    ],
  },
  {
    session: 15,
    title: 'Portfolio & Presentations',
    description: 'Assemble portfolio and practice presenting',
    week: 4,
    tools: ['Bolt.new', 'Gamma'],
    isFree: false,
    deliverable: 'Polished portfolio + 10-minute presentation',
    previewQuestions: [
      { q: 'When presenting your portfolio, focus on…', options: ['How many tools you used', 'The problems you solved and results you achieved', 'How long it took'], answer: 1 },
      { q: 'A strong portfolio presentation should be…', options: ['As long as possible', 'Concise, visual, and story-driven', 'Text-heavy with no visuals'], answer: 1 },
      { q: 'Practicing your presentation helps because…', options: ['It wastes time', 'It builds confidence and reveals weak spots', 'Clients do not care about delivery'], answer: 1 },
    ],
  },
  {
    session: 16,
    title: 'Freelancing + Certification',
    description: 'Launch your career and earn your certificate',
    week: 4,
    tools: [],
    isFree: false,
    deliverable: 'Fiverr/Upwork profiles + 90-day career plan',
    previewQuestions: [
      { q: 'The best way to get your first freelance client is…', options: ['Wait for them to find you', 'Actively reach out and showcase your portfolio', 'Lower your price to zero'], answer: 1 },
      { q: 'Fiverr and Upwork are platforms for…', options: ['Social media only', 'Finding freelance work and clients', 'Hosting websites'], answer: 1 },
      { q: 'A 90-day career plan should include…', options: ['One big goal only', 'Weekly milestones, skill targets, and income goals', 'Only the jobs you want to apply for'], answer: 1 },
    ],
  },
];
