import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { marked } from 'marked';
import { supabase, type Post } from '@/lib/supabase';

export const revalidate = 3600;

type Props = { params: Promise<{ slug: string }> };

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  const { data } = await supabase.from('posts').select('title, excerpt').eq('slug', slug).single();
  if (!data) return { title: 'Post Not Found' };
  return { title: `${data.title} | TARAhut AI Labs Blog`, description: data.excerpt };
}

function formatDate(dateStr: string) {
  return new Date(dateStr).toLocaleDateString('en-IN', {
    day: 'numeric', month: 'long', year: 'numeric',
  });
}

const CATEGORY_COLORS: Record<string, string> = {
  'AI Tools': 'bg-blue-500/15 text-blue-400',
  'Industry News': 'bg-orange-500/15 text-orange-400',
  'Machine Learning': 'bg-purple-500/15 text-purple-400',
  'AI Career': 'bg-emerald-500/15 text-emerald-400',
  'Generative AI': 'bg-pink-500/15 text-pink-400',
  'AI Business': 'bg-amber-500/15 text-amber-400',
};

export default async function BlogPostPage({ params }: Props) {
  const { slug } = await params;
  const { data: post } = await supabase
    .from('posts')
    .select('*')
    .eq('slug', slug)
    .eq('published', true)
    .single();

  if (!post) notFound();

  const p = post as Post;
  // Content is generated by our admin blog pipeline (Claude AI), not user-submitted.
  // XSS risk is minimal. If user-submitted content is ever added, sanitize with DOMPurify.
  const contentHtml = await marked(p.content, { breaks: true });

  return (
    <>
      {/* Hero */}
      <section className="bg-gradient-to-br from-[#059669] to-[#0D9488] py-14 text-white">
        <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8">
          <Link href="/blog" className="inline-flex items-center gap-1.5 text-white/70 hover:text-white text-sm mb-6 transition-colors">
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
            </svg>
            Back to Blog
          </Link>
          <span className={`inline-block rounded-full px-3 py-1 text-xs font-semibold mb-4 ${CATEGORY_COLORS[p.category] ?? 'bg-white/20 text-white'}`}>
            {p.category}
          </span>
          <h1 className="text-3xl sm:text-4xl font-bold leading-tight mb-4">{p.title}</h1>
          <div className="flex items-center gap-4 text-white/70 text-sm">
            <span>{formatDate(p.created_at)}</span>
            <span>·</span>
            <span>{p.read_time}</span>
            <span>·</span>
            <span>TARAhut AI Labs</span>
          </div>
        </div>
      </section>

      {/* Content */}
      <section className="py-14 bg-white/[0.03]">
        <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8">
          <div
            className="blog-content max-w-none text-gray-300 leading-relaxed text-lg"
            dangerouslySetInnerHTML={{ __html: contentHtml }}
          />
          <style>{`
            .blog-content h1,.blog-content h2,.blog-content h3,.blog-content h4{color:#fff;font-weight:700;margin-top:2.5rem;margin-bottom:1rem;line-height:1.3}
            .blog-content h2{font-size:1.5rem}
            .blog-content h3{font-size:1.25rem}
            .blog-content p{color:#9ca3af;line-height:1.8;margin-bottom:1.25rem}
            .blog-content strong,.blog-content b{color:#e2e8f0;font-weight:600}
            .blog-content a{color:#34d399;text-decoration:none}
            .blog-content a:hover{text-decoration:underline}
            .blog-content ul,.blog-content ol{margin:1rem 0;padding-left:1.5rem;color:#9ca3af}
            .blog-content li{margin-bottom:0.5rem;line-height:1.7}
            .blog-content blockquote{border-left:3px solid #059669;padding-left:1rem;margin:1.5rem 0;color:#94a3b8;font-style:italic}
            .blog-content code{background:rgba(0,240,255,0.08);color:#00f0ff;padding:2px 6px;border-radius:4px;font-size:0.9em}
            .blog-content pre{background:#0c0c1a;border:1px solid #1e1e3a;border-radius:8px;padding:1rem;overflow-x:auto;margin:1.5rem 0}
            .blog-content pre code{background:none;padding:0;color:#e2e8f0}
            .blog-content img{border-radius:12px;margin:1.5rem 0}
            .blog-content hr{border:none;border-top:1px solid rgba(255,255,255,0.08);margin:2rem 0}
            .blog-content table{width:100%;border-collapse:collapse;margin:1.5rem 0}
            .blog-content th{background:#0c0c1a;color:#059669;padding:10px 12px;text-align:left;border:1px solid #1e1e3a;font-size:0.85rem}
            .blog-content td{padding:10px 12px;border:1px solid #1e1e3a;color:#9ca3af}
          `}</style>

          {/* CTA */}
          <div className="mt-12 rounded-2xl bg-gradient-to-br from-[#059669]/10 to-[#0D9488]/10 border border-[#059669]/20 p-8 text-center">
            <h3 className="text-xl font-bold text-white mb-2">Want to master AI skills?</h3>
            <p className="text-gray-400 mb-5">Join TARAhut AI Labs and learn from expert-led, hands-on courses designed for Indian professionals.</p>
            <Link
              href="/courses"
              className="inline-block bg-[#059669] text-white px-6 py-3 rounded-xl font-medium hover:bg-[#047857] transition-colors"
            >
              Explore Courses
            </Link>
          </div>

          {/* Source credit */}
          {p.source_url && (
            <p className="mt-8 text-xs text-gray-600 text-center">
              Inspired by:{' '}
              <a href={p.source_url} target="_blank" rel="noopener noreferrer" className="hover:underline">
                {p.source_title ?? p.source_url}
              </a>
            </p>
          )}
        </div>
      </section>
    </>
  );
}
